import ProductDetailPage from '@/components/product-detail-page'

const product = {
  id: 'undecylenic-acid',
  name: 'Undecylenic Acid',
  subtitle: '10-Undecenoic Acid',
  tag: 'Bio-Based',
  tagColor: 'var(--brand-blue)',
  tagText: '#fff',
  image: '/undecylenic-acid.png',
  casNumber: '112-38-9',
  ecNumber: '203-965-8',
  hsnNumber: '',
  molecularFormula: 'C₁₁H₂₀O₂',
  molecularWeight: '184.28 g/mol',
  chemicalStructure: 'CH₂=CH–(CH₂)₈–COOH',
  description:
    'Undecylenic Acid is a high-purity unsaturated C11 fatty acid produced by pyrolysis of castor oil derivatives. It possesses excellent antifungal, antibacterial and surface-active properties while also serving as an important intermediate in pharmaceutical, cosmetic, agricultural and specialty chemical industries. High GC purity (typically ≥99.5%) with consistent batch-to-batch quality.',
  specifications: [
    { parameter: 'Appearance', value: 'Clear colorless to pale yellow liquid or low melting solid' },
    { parameter: 'Odour', value: 'Mild characteristic fatty odour' },
    { parameter: 'Purity (GC)', value: '≥99.0% (Typical ≥99.5%)' },
    { parameter: 'Acid Value', value: '296–304 mg KOH/g' },
    { parameter: 'Iodine Value', value: '131–138 g I₂/100g' },
    { parameter: 'Moisture', value: '≤0.20%' },
    { parameter: 'Colour (APHA)', value: '≤100' },
    { parameter: 'Free Mineral Acid', value: 'Nil' },
    { parameter: 'Density (25°C)', value: '0.910–0.913 g/cm³' },
    { parameter: 'Refractive Index (25°C)', value: '1.446–1.448' },
    { parameter: 'Boiling Point', value: '~295°C' },
    { parameter: 'Melting Point', value: '21–24°C' },
    { parameter: 'Flash Point', value: '~140°C (Closed Cup)' },
    { parameter: 'Solubility', value: 'Insoluble in water; soluble in alcohols, ethers, ketones and hydrocarbons' },
    { parameter: 'Shelf Life', value: '24 months under recommended storage conditions' },
  ],
  applications: [
    'Antifungal creams, powders, skin ointments, foot sprays, nail solutions and medicated soaps (5–25% concentration)',
    'Active against athlete\'s foot, ringworm, jock itch, tinea infections and fungal skin infections',
    'Anti-dandruff formulations, deodorants, foot care creams and odour-control products',
    'Agricultural bio-based fungicides — active against powdery mildew, downy mildew, Alternaria, Botrytis, Fusarium',
    'Seed treatment, foliar sprays, post-harvest disease control and fruit coating formulations',
    'Veterinary hoof care, antifungal sprays, animal skin creams and pet shampoos',
    'Raw material for zinc undecylenate, sodium undecylenate, calcium undecylenate and esters',
    'Polymer modification, UV-curable resins, adhesive intermediates and reactive diluents',
    'Fragrance chemicals, corrosion inhibitors and specialty surfactants',
    'Lubricant additives and biocide synthesis',
  ],
  keyProperties: [
    'Broad-spectrum antifungal activity',
    'Excellent activity against dermatophytes',
    'Mild antibacterial activity',
    'Good hydrophobicity',
    'High chemical reactivity through terminal double bond',
    'Excellent intermediate for specialty synthesis',
    'Renewable raw material origin from castor oil',
    'Low mammalian toxicity',
  ],
  downstreamProducts: [
    'Zinc Undecylenate',
    'Sodium Undecylenate',
    'Undecylenoyl Chloride',
    'Undecylenamide',
    'Undecylenate Esters',
    'Undecylenyl Alcohol',
    'Specialty Polymers',
    'Fragrance Intermediates',
    'Agrochemical Intermediates',
  ],
  efficacy: [
    { property: 'Antifungal Activity', performance: 'Excellent' },
    { property: 'Antibacterial Activity', performance: 'Moderate' },
    { property: 'Anti-biofilm Activity', performance: 'Good' },
    { property: 'Plant Disease Control', performance: 'Good–Excellent (when formulated)' },
    { property: 'Deodorizing Property', performance: 'Excellent' },
    { property: 'Surface Activity', performance: 'Moderate' },
    { property: 'Chemical Reactivity', performance: 'Excellent' },
  ],
  packaging: [
    '25 kg HDPE Carboys',
    '50 kg HDPE Drums',
    '180 kg HDPE Drums',
    '200 kg MS Drums (lined)',
    'IBC Containers',
    'Bulk Tankers',
    'Custom packaging available upon request',
  ],
  storage: 'Store in tightly closed containers in a cool, dry place away from direct sunlight and oxidizing agents. Recommended storage temperature: 15–35°C.',
  industries: [
    'Pharmaceutical',
    'Personal Care & Cosmetics',
    'Agriculture',
    'Veterinary',
    'Specialty Chemicals',
    'Polymer & Resin',
    'Lubricants',
    'Fine Chemicals',
  ],
  compatibility: [
    'Vegetable oils',
    'Mineral oils',
    'Alcohols & Glycols',
    'Non-ionic surfactants',
    'Silicone fluids',
    'Fatty alcohols',
    'Fatty acid esters',
  ],
}

export const metadata = {
  title: 'Undecylenic Acid (10-Undecenoic Acid) | GreenChem Global',
  description:
    'High-purity Undecylenic Acid — CAS 112-38-9. ≥99.5% GC purity bio-based C11 fatty acid for antifungal pharmaceuticals, cosmetics, agriculture, and specialty chemicals.',
}

export default function UndecylenicAcidPage() {
  return <ProductDetailPage product={product} />
}
